### ISSUE TITLE
Classes generated in the wrong package

### ISSUE THREAD

**Issue by priyakar** [burakeregar/KotlinMvpTemplate#1]
I have a java and kotlin package in my project. Im trying to generate the new files under the kotlin package but the files go to the java package instead. I have 2 soruceSets in my app gradle like this : main.java.srcDirs += 'src/main/kotlin'

**Comment by burakeregar** [comment]
It can be Android Studio's bug. Can you please switch from Android structure to Project structure and check that package name again?

![ekran resmi 2017-05-31 00 51 29](https://cloud.githubusercontent.com/assets/13684457/26606694/90e53a9e-459b-11e7-9987-2d634c7a5e5c.png)

**Comment by priyakar** [comment]
I did that. I think android studio doesnt support creating a new activity old fashioned way if you have kotlin as your sourceDir

**Comment by burakeregar** [comment]
I think they're gonna fix it. If you attempt to rename java package in Android mode, you can see that it's Kotlin indeed.
![ekran resmi 2017-05-31 01 06 28](https://cloud.githubusercontent.com/assets/13684457/26607120/a1e7862e-459d-11e7-9a0e-31bd74b78413.png)

**Comment by priyakar** [comment]
Yep. I hope they fix it soon. Really like your idea and would like to use it soon :) Thanks
